dist: xenial
language: python

install:
  - pip install -q tox==3.2.1 coveralls==1.7

script:
  - coverage erase
  - tox
after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - cedric@onekiloparsec.dev
